# INFO 370 Lab 6
*Name: Brian Park*

In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf

## 1. Logistic Regression 

1. load file titanic.csv, and do quick sanity checks. Note that age has ∼ 260 missing observations, the other relevant variables are pretty good.
2. Based on the survivors’ accounts, described above, which variables do you think are the most important ones to describe titanic survival?
3. Create a new dummy variable child, that is 1 if the passenger was youger than 14 and 0 otherwise. Hint: you can use np.where or just a logical operation.
4. Estimate a multiple logistic regression model where you explain survival by these variables. Remember: pclass should be treated as categorical! Wrap it into C().
5. Interpret the results. Did men or women, old or young have larger chances to survive?
6. Based on the results above, explain what can you tell about the last hours on Titanic. Are the survivors’ accounts broadly accurate? Did the order break down? Can you find anything else interesting?

In [59]:
#1-1
titanic = pd.read_csv("../data/titanic.csv.bz2", sep = ',')
titanic.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [60]:
#1-1
titanic.isna().sum()

pclass          0
survived        0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64

In [61]:
#1-1
titanic.shape

(1309, 14)

In [62]:
#1-2

Based on the survivors’ accounts, I think that variables `survived`, `sex`, `age`, and `pclass` are the most
important ones to describe titanic survival.

In [63]:
#1-3
titanic["child"] = np.where(titanic.age < 14, 1, 0)
titanic.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  child  
0                     St Louis, MO      0  
1  Montreal, PQ / Chesterville, ON      1  
2  Montreal, PQ / Chesterville, ON      1  
3  Montreal, PQ / Chesterville, ON      0  
4  Montreal, PQ / Chesterville, ON      0

In [64]:
#1-4
m = smf.logit("survived ~ C(pclass) + sex + child", data = titanic).fit()
m.get_margeff().summary()

Optimization terminated successfully.
         Current function value: 0.471565
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
        Logit Marginal Effects       
=====================================
Dep. Variable:               survived
Method:                          dydx
At:                           overall
==================================================================================
                    dy/dx    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
C(pclass)[T.2]    -0.1462      0.030     -4.934      0.000      -0.204      -0.088
C(pclass)[T.3]    -0.2799      0.023    -12.013      0.000      -0.326      -0.234
sex[T.male]       -0.3825      0.011    -33.641      0.000      -0.405      -0.360
child              0.1863      0.038      4.842      0.000       0.111       0.262
==================================================================================
"""

In [65]:
#1-5-C(pclass)[T.2]

2nd class people have a 14.62 pct pts less chance to survive than 1st class people.

In [66]:
#1-5-C(pclass)[T.3]

3rd class people have a 27.99 pct pts less chance to survive than 1st class people.

In [67]:
#1-5-sex[T.male]

Males have a 38.25 pct pts less chance to survive than females.

In [68]:
#1-5-child

People younger than 14 have a 18.64 pct pts more chance to survive than those older or equal to 14.

In [69]:
#1-6

Based on the results computed above, the survivors' accounts were fairly accurate. For example, women and children were first to get on boats while men stayed on board which predicts men to have less chance to survive and fairly matches the result that men had a 38.25 pct pts less chance to survive than females. Also, it fairly matches that people younger than 14 or children had a 18.64 pct pts more chance to survive than those older or equal to 14. However, ironically, 2nd and 3rd class people including women and children who could hardly reach up to the boat deck had less chance to survive than 1st class people which quite contradicts the result that women and children without regarding their classes had more chance to survive. I also found it interesting that some other variables or factors might affect the titanic survival rate in different situations.